---
repos:
  # pre-commit picks up coding errors prior to committing them
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-case-conflict
      - id: end-of-file-fixer
        exclude_types:
          - "gif"
      - id: trailing-whitespace

  # gitleaks detects hard coded secrets
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.8.12
    hooks:
      - id: gitleaks

  # actionlint is a static checker for GitHub Actions workflow files
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.15
    hooks:
      - id: actionlint
