baseURL = "https://www.3ware.co.uk/"
languageCode = "en-gb"
title = "3ware Ltd"
theme = "introduction"

[params]
themeStyle = "dark"
favicon = "img/favicon.ico"
fadeIn = false
email = "contact@3ware.co.uk"

[params.home]
introHeight = "medium"
showLatest = true
showAllPosts = false
localTime = true
timeZone = "Europe/London"
timeFormat = "en-GB"

[[params.social]]
url = "https://linkedin.com/company/3ware"
icon = "linkedin-in"                       # icon name without the 'fa-'
icon_pack = "fab"

[[params.social]]
url = "https://github.com/3ware"
icon = "github"                  # icon name without the 'fa-'
icon_pack = "fab"

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
# For styles, see https://xyproto.github.io/splash/docs/longer/all.html
style = "gruvbox"
tabWidth = 4

[languages]
[languages.en]
languageName = "English"
languageCode = "en-gb"
contentDir = "content/en"
weight = 0
title = "3ware Ltd"
[languages.en.params]
description = "3ware Ltd is a specialist network and security consultancy with 18 years of industry experience. Our main focus is helping clients with Data Centre design, cloud migrations and digital transformation projects in the Public Sector and the Enterprise." # Max 160 characters show in search results
footerText = "Copyright &copy; 2021-2022 3ware Ltd"
