name: commitlint
on:
  pull_request:

jobs:
  main:
    name: Validate commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2.0.3
        with:
          failOnWarnings: true
