# This file is managed by terraform and should be edited directly

name: Validate PR title
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  conventional-pr-title:
    permissions:
      pull-requests: read
    uses: 3ware/workflows/.github/workflows/pr-title.yaml@v1.7.0
