name: Publish Website

on:
  release:
    types: [published]
  workflow_dispatch: {}

# Disable permissions for all available scopes
permissions: {}

jobs:
  build-website:
    name: Build
    uses: 3ware/www-src/.github/workflows/hugo.yaml@2e5314429b97aecc4354ba42a5ba0fb0c287b1ec # v2.0.0

  publish-website:
    needs: [build-website]
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 10
    steps:
      - name: Publish
        uses: peaceiris/actions-gh-pages@a16b61f0780be556cf97931905d261429ee79342 #v4.0.0
        with:
          deploy_key: ${{ secrets.ACTION_DEPLOY_KEY }}
          external_repository: 3ware/www-public
          publish_dir: ./public # This is the source dir. ./public is the default.
          destination_dir: ./docs
          keep_files: true
          user_name: 3ware-release[bot]
          user_email: 3ware-release[bot]@users.noreply.github.com
          publish_branch: main
          commit_message: ${{ github.event.tag_name }}
