name: Publish Website

on:
  release:
    types: [published]

# Disable permissions for all available scopes
permissions: {}

jobs:
  build-website:
    name: Build
    uses: 3ware/www-src/.github/workflows/hugo.yaml@92f6a8455c7aef8dd906e7c0f5259ee21dcd80c9 #v2.1.0

  publish-website:
    name: Publish
    needs: [build-website]
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 10
    steps:
      - name: Download artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: 3ware-website
          path: ./public

      - name: Publish
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          deploy_key: ${{ secrets.ACTION_DEPLOY_KEY }}
          external_repository: 3ware/www-public
          publish_dir: ./public # This is the source dir. ./public is the default.
          destination_dir: ./docs
          keep_files: true
          user_name: 3ware-release[bot]
          user_email: 3ware-release[bot]@users.noreply.github.com
          publish_branch: main
          commit_message: ${{ github.event.tag_name }}
