name: Publish Website

on:
  release:
    types: [published]

# Disable permissions for all available scopes
permissions: {}

jobs:
  publish-website:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Build website
        uses: ./.github/workflows/hugo.yaml

      - name: Deploy website to www-public
        uses: peaceiris/actions-gh-pages@a16b61f0780be556cf97931905d261429ee79342 #v4.0.0
        with:
          deploy_key: ${{ secrets.ACTION_DEPLOY_KEY }}
          external_repository: 3ware/www-public
          publish_dir: ./public # This is the source dir. ./public is the default.
          destination_dir: ./docs
          keep_files: true
          user_name: 3ware-release[bot]
          user_email: 3ware-release[bot]@users.noreply.github.com
          publish_branch: main
          commit_message: ${{ github.event.tag_name }}
