# This file is managed by terraform and should not be updated directly

name: Semantic Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  semantic-release:
    uses: 3ware/workflows/.github/workflows/semantic-release.yaml@v1.7.0
    secrets: inherit
