name: Test Build
on:
  pull_request:
    types: [opened, synchronize]

# Disable permissions for all available scopes
permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write # not required (see slack) but produces an error in the logs
      # https://trunkcommunity.slack.com/archives/C04GAE5EA5S/p1677846825881319?thread_ts=1676214812.584879&cid=C04GAE5EA5S
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          persist-credentials: true # lint fails to authenticate when false

      - name: Dependency Review
        uses: actions/dependency-review-action@4901385134134e04cec5fbe5ddfe3b2c5bd5d976 # v4.0.0

  build:
    # Job name should be the same as the called workflow name for required status
    # check to match. In this case job level `name: Build` matches workflow level
    # `name: Build` in hugo.yaml
    name: Build
    needs: [test]
    uses: 3ware/www-src/.github/workflows/hugo.yaml@92f6a8455c7aef8dd906e7c0f5259ee21dcd80c9 #v2.1.0
